import { MoviesByGenreType } from "./types";

export const moviesByGenre: Array<MoviesByGenreType> = [
  {
    genreId: 12,
    genreName: "Adventure",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
          genre_ids: [12, 14, 28],
          id: 122,
          original_language: "en",
          original_title: "The Lord of the Rings: The Return of the King",
          overview:
            "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
          popularity: 18.4545,
          poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
          release_date: "2003-12-17",
          title: "The Lord of the Rings: The Return of the King",
          video: false,
          vote_average: 8.486,
          vote_count: 25151,
        },
        {
          adult: false,
          backdrop_path: "/l33oR0mnvf20avWyIMxW02EtQxn.jpg",
          genre_ids: [12, 18, 878],
          id: 157336,
          original_language: "en",
          original_title: "Interstellar",
          overview:
            "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
          popularity: 35.8128,
          poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
          release_date: "2014-11-05",
          title: "Interstellar",
          video: false,
          vote_average: 8.455,
          vote_count: 37289,
        },
        {
          adult: false,
          backdrop_path: "/x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg",
          genre_ids: [12, 14, 28],
          id: 120,
          original_language: "en",
          original_title: "The Lord of the Rings: The Fellowship of the Ring",
          overview:
            "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
          popularity: 25.2971,
          poster_path: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
          release_date: "2001-12-18",
          title: "The Lord of the Rings: The Fellowship of the Ring",
          video: false,
          vote_average: 8.423,
          vote_count: 26065,
        },
        {
          adult: false,
          backdrop_path: "/jfEOzpsjc6JDlKhUHb4toWQPt.jpg",
          genre_ids: [12, 14, 28],
          id: 121,
          original_language: "en",
          original_title: "The Lord of the Rings: The Two Towers",
          overview:
            "Frodo Baggins and the other members of the Fellowship continue on their sacred quest to destroy the One Ring--but on separate paths. Their destinies lie at two towers--Orthanc Tower in Isengard, where the corrupt wizard Saruman awaits, and Sauron's fortress at Barad-dur, deep within the dark lands of Mordor. Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.",
          popularity: 15.902,
          poster_path: "/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
          release_date: "2002-12-18",
          title: "The Lord of the Rings: The Two Towers",
          video: false,
          vote_average: 8.407,
          vote_count: 22661,
        },
        {
          adult: false,
          backdrop_path: "/8mnXR9rey5uQ08rZAvzojKWbDQS.jpg",
          genre_ids: [16, 28, 12, 878],
          id: 324857,
          original_language: "en",
          original_title: "Spider-Man: Into the Spider-Verse",
          overview:
            'Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson "Kingpin" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension.',
          popularity: 18.0963,
          poster_path: "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
          release_date: "2018-12-06",
          title: "Spider-Man: Into the Spider-Verse",
          video: false,
          vote_average: 8.399,
          vote_count: 16210,
        },
        {
          adult: false,
          backdrop_path: "/nv5wwZou159v5OC61i4ElR7OqyY.jpg",
          genre_ids: [14, 16, 12],
          id: 4935,
          original_language: "ja",
          original_title: "ハウルの動く城",
          overview:
            "Sophie, a young milliner, is turned into an elderly woman by a witch who enters her shop and curses her. She encounters a wizard named Howl and gets caught up in his resistance to fighting for the king.",
          popularity: 17.3977,
          poster_path: "/23hUJh7JdO23SpgUB5oiFDQk2wX.jpg",
          release_date: "2004-09-09",
          title: "Howl's Moving Castle",
          video: false,
          vote_average: 8.397,
          vote_count: 10354,
        },
        {
          adult: false,
          backdrop_path: "/kgjvZgs6cV2v5bigzzzWqJ9EMGs.jpg",
          genre_ids: [12, 28, 878],
          id: 1891,
          original_language: "en",
          original_title: "The Empire Strikes Back",
          overview:
            "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.",
          popularity: 8.9603,
          poster_path: "/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
          release_date: "1980-05-20",
          title: "The Empire Strikes Back",
          video: false,
          vote_average: 8.396,
          vote_count: 17478,
        },
      ],
    },
  },

  {
    genreId: 14,
    genreName: "Fantasy",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg",
          genre_ids: [16, 10751, 14],
          id: 129,
          original_language: "ja",
          original_title: "千と千尋の神隠し",
          overview:
            "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
          popularity: 18.5441,
          poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
          release_date: "2001-07-20",
          title: "Spirited Away",
          video: false,
          vote_average: 8.536,
          vote_count: 17212,
        },
        {
          adult: false,
          backdrop_path: "/amZavErrjrdgDwhsIdpWxHNenIx.jpg",
          genre_ids: [14, 18, 80],
          id: 497,
          original_language: "en",
          original_title: "The Green Mile",
          overview:
            "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
          popularity: 16.8896,
          poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
          release_date: "1999-12-10",
          title: "The Green Mile",
          video: false,
          vote_average: 8.505,
          vote_count: 18143,
        },
        {
          adult: false,
          backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
          genre_ids: [12, 14, 28],
          id: 122,
          original_language: "en",
          original_title: "The Lord of the Rings: The Return of the King",
          overview:
            "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
          popularity: 18.4545,
          poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
          release_date: "2003-12-17",
          title: "The Lord of the Rings: The Return of the King",
          video: false,
          vote_average: 8.486,
          vote_count: 25151,
        },
        {
          adult: false,
          backdrop_path: "/alQqTpmEkxSLgajfEYTsTH6nAKB.jpg",
          genre_ids: [35, 18, 14],
          id: 40096,
          original_language: "pt",
          original_title: "O Auto da Compadecida",
          overview:
            "The lively João Grilo and the sly Chicó are poor guys living in the hinterland who cheat a bunch of people in a small town in Northeastern Brazil. When they die, they have to be judged by Christ, the Devil and the Virgin Mary before they are admitted to paradise.",
          popularity: 2.0711,
          poster_path: "/aovknfdLnFp1IiWi3yvTAg8Gm5k.jpg",
          release_date: "2000-09-15",
          title: "A Dog's Will",
          video: false,
          vote_average: 8.4,
          vote_count: 1165,
        },
        {
          adult: false,
          backdrop_path: "/x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg",
          genre_ids: [12, 14, 28],
          id: 120,
          original_language: "en",
          original_title: "The Lord of the Rings: The Fellowship of the Ring",
          overview:
            "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
          popularity: 25.2971,
          poster_path: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
          release_date: "2001-12-18",
          title: "The Lord of the Rings: The Fellowship of the Ring",
          video: false,
          vote_average: 8.423,
          vote_count: 26065,
        },
        {
          adult: false,
          backdrop_path: "/jfEOzpsjc6JDlKhUHb4toWQPt.jpg",
          genre_ids: [12, 14, 28],
          id: 121,
          original_language: "en",
          original_title: "The Lord of the Rings: The Two Towers",
          overview:
            "Frodo Baggins and the other members of the Fellowship continue on their sacred quest to destroy the One Ring--but on separate paths. Their destinies lie at two towers--Orthanc Tower in Isengard, where the corrupt wizard Saruman awaits, and Sauron's fortress at Barad-dur, deep within the dark lands of Mordor. Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.",
          popularity: 15.902,
          poster_path: "/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
          release_date: "2002-12-18",
          title: "The Lord of the Rings: The Two Towers",
          video: false,
          vote_average: 8.407,
          vote_count: 22661,
        },
        {
          adult: false,
          backdrop_path: "/nv5wwZou159v5OC61i4ElR7OqyY.jpg",
          genre_ids: [14, 16, 12],
          id: 4935,
          original_language: "ja",
          original_title: "ハウルの動く城",
          overview:
            "Sophie, a young milliner, is turned into an elderly woman by a witch who enters her shop and curses her. She encounters a wizard named Howl and gets caught up in his resistance to fighting for the king.",
          popularity: 17.3977,
          poster_path: "/23hUJh7JdO23SpgUB5oiFDQk2wX.jpg",
          release_date: "2004-09-09",
          title: "Howl's Moving Castle",
          video: false,
          vote_average: 8.397,
          vote_count: 10354,
        },
      ],
    },
  },

  {
    genreId: 16,
    genreName: "Animation",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg",
          genre_ids: [16, 10751, 14],
          id: 129,
          original_language: "ja",
          original_title: "千と千尋の神隠し",
          overview:
            "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
          popularity: 18.5441,
          poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
          release_date: "2001-07-20",
          title: "Spirited Away",
          video: false,
          vote_average: 8.536,
          vote_count: 17212,
        },
        {
          adult: false,
          backdrop_path: "/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg",
          genre_ids: [16, 10749, 18],
          id: 372058,
          original_language: "ja",
          original_title: "君の名は。",
          overview:
            "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
          popularity: 20.7912,
          poster_path: "/8GJsy7w7frGquw1cy9jasOGNNI1.jpg",
          release_date: "2016-08-26",
          title: "Your Name.",
          video: false,
          vote_average: 8.482,
          vote_count: 11812,
        },
        {
          adult: false,
          backdrop_path: "/tDFvXn4tane9lUvFAFAUkMylwSr.jpg",
          genre_ids: [16, 18, 10752],
          id: 12477,
          original_language: "ja",
          original_title: "火垂るの墓",
          overview:
            "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
          popularity: 0.0094,
          poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
          release_date: "1988-04-16",
          title: "Grave of the Fireflies",
          video: false,
          vote_average: 8.448,
          vote_count: 5924,
        },
        {
          adult: false,
          backdrop_path: "/8mnXR9rey5uQ08rZAvzojKWbDQS.jpg",
          genre_ids: [16, 28, 12, 878],
          id: 324857,
          original_language: "en",
          original_title: "Spider-Man: Into the Spider-Verse",
          overview:
            'Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson "Kingpin" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension.',
          popularity: 18.0963,
          poster_path: "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
          release_date: "2018-12-06",
          title: "Spider-Man: Into the Spider-Verse",
          video: false,
          vote_average: 8.399,
          vote_count: 16210,
        },
        {
          adult: false,
          backdrop_path: "/nv5wwZou159v5OC61i4ElR7OqyY.jpg",
          genre_ids: [14, 16, 12],
          id: 4935,
          original_language: "ja",
          original_title: "ハウルの動く城",
          overview:
            "Sophie, a young milliner, is turned into an elderly woman by a witch who enters her shop and curses her. She encounters a wizard named Howl and gets caught up in his resistance to fighting for the king.",
          popularity: 17.3977,
          poster_path: "/23hUJh7JdO23SpgUB5oiFDQk2wX.jpg",
          release_date: "2004-09-09",
          title: "Howl's Moving Castle",
          video: false,
          vote_average: 8.397,
          vote_count: 10354,
        },
        {
          adult: false,
          backdrop_path: "/5lAMQMWpXMsirvtLLvW7cJgEPkU.jpg",
          genre_ids: [16, 18, 10749],
          id: 378064,
          original_language: "ja",
          original_title: "映画 聲の形",
          overview:
            "Shouya Ishida starts bullying the new girl in class, Shouko Nishimiya, because she is deaf. But as the teasing continues, the rest of the class starts to turn on Shouya for his lack of compassion. When they leave elementary school, Shouko and Shouya do not speak to each other again... until an older, wiser Shouya, tormented by his past behaviour, decides he must see Shouko once more. He wants to atone for his sins, but is it already too late...?",
          popularity: 9.9964,
          poster_path: "/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg",
          release_date: "2016-09-17",
          title: "A Silent Voice: The Movie",
          video: false,
          vote_average: 8.4,
          vote_count: 4147,
        },
      ],
    },
  },

  {
    genreId: 18,
    genreName: "Drama",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
          genre_ids: [18, 80],
          id: 278,
          original_language: "en",
          original_title: "The Shawshank Redemption",
          overview:
            "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
          popularity: 32.9479,
          poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
          release_date: "1994-09-23",
          title: "The Shawshank Redemption",
          video: false,
          vote_average: 8.711,
          vote_count: 28443,
        },
        {
          adult: false,
          backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
          genre_ids: [18, 80],
          id: 238,
          original_language: "en",
          original_title: "The Godfather",
          overview:
            "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
          popularity: 36.0976,
          poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
          release_date: "1972-03-14",
          title: "The Godfather",
          video: false,
          vote_average: 8.686,
          vote_count: 21540,
        },
        {
          adult: false,
          backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
          genre_ids: [18, 80],
          id: 240,
          original_language: "en",
          original_title: "The Godfather Part II",
          overview:
            "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
          popularity: 16.1032,
          poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
          release_date: "1974-12-20",
          title: "The Godfather Part II",
          video: false,
          vote_average: 8.571,
          vote_count: 13007,
        },
        {
          adult: false,
          backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
          genre_ids: [18, 36, 10752],
          id: 424,
          original_language: "en",
          original_title: "Schindler's List",
          overview:
            "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
          popularity: 12.5664,
          poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
          release_date: "1993-12-15",
          title: "Schindler's List",
          video: false,
          vote_average: 8.564,
          vote_count: 16479,
        },

        {
          adult: false,
          backdrop_path: "/bxgTSUenZDHNFerQ1whRKplrMKF.jpg",
          genre_ids: [18],
          id: 389,
          original_language: "en",
          original_title: "12 Angry Men",
          overview:
            "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
          popularity: 17.1905,
          poster_path: "/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg",
          release_date: "1957-04-10",
          title: "12 Angry Men",
          video: false,
          vote_average: 8.548,
          vote_count: 9186,
        },
        {
          adult: false,
          backdrop_path: "/enNubozHn9pXi0ycTVYUWfpHZm.jpg",
          genre_ids: [18, 28, 80, 53],
          id: 155,
          original_language: "en",
          original_title: "The Dark Knight",
          overview:
            "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
          popularity: 20.3922,
          poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
          release_date: "2008-07-16",
          title: "The Dark Knight",
          video: false,
          vote_average: 8.52,
          vote_count: 33960,
        },
        {
          adult: false,
          backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
          genre_ids: [35, 18, 10749],
          id: 19404,
          original_language: "hi",
          original_title: "दिलवाले दुल्हनिया ले जायेंगे",
          overview:
            "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
          popularity: 8.0918,
          poster_path: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
          release_date: "1995-10-20",
          title: "Dilwale Dulhania Le Jayenge",
          video: false,
          vote_average: 8.517,
          vote_count: 4490,
        },
        {
          adult: false,
          backdrop_path: "/amZavErrjrdgDwhsIdpWxHNenIx.jpg",
          genre_ids: [14, 18, 80],
          id: 497,
          original_language: "en",
          original_title: "The Green Mile",
          overview:
            "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
          popularity: 16.8896,
          poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
          release_date: "1999-12-10",
          title: "The Green Mile",
          video: false,
          vote_average: 8.505,
          vote_count: 18143,
        },
        {
          adult: false,
          backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
          genre_ids: [35, 53, 18],
          id: 496243,
          original_language: "ko",
          original_title: "기생충",
          overview:
            "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
          popularity: 22.8694,
          poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
          release_date: "2019-05-30",
          title: "Parasite",
          video: false,
          vote_average: 8.499,
          vote_count: 19135,
        },
        {
          adult: false,
          backdrop_path: "/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg",
          genre_ids: [16, 10749, 18],
          id: 372058,
          original_language: "ja",
          original_title: "君の名は。",
          overview:
            "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
          popularity: 20.7912,
          poster_path: "/8GJsy7w7frGquw1cy9jasOGNNI1.jpg",
          release_date: "2016-08-26",
          title: "Your Name.",
          video: false,
          vote_average: 8.482,
          vote_count: 11812,
        },
        {
          adult: false,
          backdrop_path: "/tlEFuIlaxRPXIYVHXbOSAMCfWqk.jpg",
          genre_ids: [35, 18, 10749],
          id: 13,
          original_language: "en",
          original_title: "Forrest Gump",
          overview:
            "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
          popularity: 17.8749,
          poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
          release_date: "1994-06-23",
          title: "Forrest Gump",
          video: false,
          vote_average: 8.468,
          vote_count: 28295,
        },
        {
          adult: false,
          backdrop_path: "/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg",
          genre_ids: [28, 18],
          id: 346,
          original_language: "ja",
          original_title: "七人の侍",
          overview:
            "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
          popularity: 8.0693,
          poster_path: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
          release_date: "1954-04-26",
          title: "Seven Samurai",
          video: false,
          vote_average: 8.456,
          vote_count: 3910,
        },
        {
          adult: false,
          backdrop_path: "/l33oR0mnvf20avWyIMxW02EtQxn.jpg",
          genre_ids: [12, 18, 878],
          id: 157336,
          original_language: "en",
          original_title: "Interstellar",
          overview:
            "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
          popularity: 35.8128,
          poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
          release_date: "2014-11-05",
          title: "Interstellar",
          video: false,
          vote_average: 8.455,
          vote_count: 37289,
        },
        {
          adult: false,
          backdrop_path: "/7TF4p86ZafnxFuNqWdhpHXFO244.jpg",
          genre_ids: [18, 80],
          id: 769,
          original_language: "en",
          original_title: "GoodFellas",
          overview:
            "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
          popularity: 13.653,
          poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
          release_date: "1990-09-12",
          title: "GoodFellas",
          video: false,
          vote_average: 8.454,
          vote_count: 13427,
        },
        {
          adult: false,
          backdrop_path: "/tDFvXn4tane9lUvFAFAUkMylwSr.jpg",
          genre_ids: [16, 18, 10752],
          id: 12477,
          original_language: "ja",
          original_title: "火垂るの墓",
          overview:
            "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
          popularity: 0.0094,
          poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
          release_date: "1988-04-16",
          title: "Grave of the Fireflies",
          video: false,
          vote_average: 8.448,
          vote_count: 5924,
        },
        {
          adult: false,
          backdrop_path: "/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg",
          genre_ids: [35, 18],
          id: 637,
          original_language: "it",
          original_title: "La vita è bella",
          overview:
            "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
          popularity: 10.5656,
          poster_path: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
          release_date: "1997-12-20",
          title: "Life Is Beautiful",
          video: false,
          vote_average: 8.447,
          vote_count: 13400,
        },
        {
          adult: false,
          backdrop_path: "/xRyINp9KfMLVjRiO5nCsoRDdvvF.jpg",
          genre_ids: [18],
          id: 550,
          original_language: "en",
          original_title: "Fight Club",
          overview:
            'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
          popularity: 21.5809,
          poster_path: "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
          release_date: "1999-10-15",
          title: "Fight Club",
          video: false,
          vote_average: 8.438,
          vote_count: 30380,
        },
        {
          adult: false,
          backdrop_path: "/k3SBILYxHRgjORb5tbvA5dm2N4h.jpg",
          genre_ids: [18, 10749],
          id: 11216,
          original_language: "it",
          original_title: "Nuovo Cinema Paradiso",
          overview:
            "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
          popularity: 5.3075,
          poster_path: "/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg",
          release_date: "1988-11-17",
          title: "Cinema Paradiso",
          video: false,
          vote_average: 8.4,
          vote_count: 4544,
        },
        {
          adult: false,
          backdrop_path: "/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg",
          genre_ids: [10751, 18],
          id: 667257,
          original_language: "es",
          original_title: "Cosas imposibles",
          overview:
            "After the death of her abusive husband, Matilde finds her new best friend in Miguel, her young, insecure, and disoriented neighbor.",
          popularity: 0.9881,
          poster_path: "/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg",
          release_date: "2021-06-17",
          title: "Impossible Things",
          video: false,
          vote_average: 8.43,
          vote_count: 410,
        },
        {
          adult: false,
          backdrop_path: "/alQqTpmEkxSLgajfEYTsTH6nAKB.jpg",
          genre_ids: [35, 18, 14],
          id: 40096,
          original_language: "pt",
          original_title: "O Auto da Compadecida",
          overview:
            "The lively João Grilo and the sly Chicó are poor guys living in the hinterland who cheat a bunch of people in a small town in Northeastern Brazil. When they die, they have to be judged by Christ, the Devil and the Virgin Mary before they are admitted to paradise.",
          popularity: 2.0711,
          poster_path: "/aovknfdLnFp1IiWi3yvTAg8Gm5k.jpg",
          release_date: "2000-09-15",
          title: "A Dog's Will",
          video: false,
          vote_average: 8.4,
          vote_count: 1165,
        },
        {
          adult: false,
          backdrop_path: "/uvitbjFU4JqvMwIkMWHp69bmUzG.jpg",
          genre_ids: [18, 80],
          id: 598,
          original_language: "pt",
          original_title: "Cidade de Deus",
          overview:
            "In the poverty-stricken favelas of Rio de Janeiro in the 1970s, two young men choose different paths. Rocket is a budding photographer who documents the increasing drug-related violence of his neighborhood, while José “Zé” Pequeno is an ambitious drug dealer diving into a dangerous life of crime.",
          popularity: 7.6888,
          poster_path: "/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg",
          release_date: "2002-08-30",
          title: "City of God",
          video: false,
          vote_average: 8.43,
          vote_count: 7684,
        },
        {
          adult: false,
          backdrop_path: "/nC3IjYhUgZWgfKfFX0ygMigFwgc.jpg",
          genre_ids: [28, 18, 36],
          id: 14537,
          original_language: "ja",
          original_title: "切腹",
          overview:
            "Down-on-his-luck veteran Tsugumo Hanshirō enters the courtyard of the prosperous House of Iyi. Unemployed, and with no family, he hopes to find a place to commit seppuku—and a worthy second to deliver the coup de grâce in his suicide ritual. The senior counselor for the Iyi clan questions the ronin’s resolve and integrity, suspecting Hanshirō of seeking charity rather than an honorable end. What follows is a pair of interlocking stories which lay bare the difference between honor and respect, and promises to examine the legendary foundations of the Samurai code.",
          popularity: 4.7752,
          poster_path: "/5konZnIbcAxZjP616Cz5o9bKEfW.jpg",
          release_date: "1962-09-15",
          title: "Harakiri",
          video: false,
          vote_average: 8.423,
          vote_count: 1088,
        },
        {
          adult: false,
          backdrop_path: "/uA8eSNAUUUyfHNIrG4h0zHxzt9W.jpg",
          genre_ids: [18],
          id: 510,
          original_language: "en",
          original_title: "One Flew Over the Cuckoo's Nest",
          overview:
            "A petty criminal fakes insanity to serve his sentence in a mental ward rather than prison. He soon finds himself as a leader to the other patients—and an enemy to the cruel, domineering nurse who runs the ward.",
          popularity: 9.5155,
          poster_path: "/kjWsMh72V6d8KRLV4EOoSJLT1H7.jpg",
          release_date: "1975-11-19",
          title: "One Flew Over the Cuckoo's Nest",
          video: false,
          vote_average: 8.414,
          vote_count: 10809,
        },
        {
          adult: false,
          backdrop_path: "/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg",
          genre_ids: [10749, 18],
          id: 696374,
          original_language: "en",
          original_title: "Gabriel's Inferno",
          overview:
            "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
          popularity: 2.3924,
          poster_path: "/yXRoyYzIo17HfANn07oXYdyBy4h.jpg",
          release_date: "2020-05-29",
          title: "Gabriel's Inferno",
          video: false,
          vote_average: 8.411,
          vote_count: 2424,
        },
        {
          adult: false,
          backdrop_path: "/uPYa165sraN2c8gZBM9C47g3JoU.jpg",
          genre_ids: [18, 80],
          id: 311,
          original_language: "en",
          original_title: "Once Upon a Time in America",
          overview:
            "A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.",
          popularity: 8.8344,
          poster_path: "/i0enkzsL5dPeneWnjl1fCWm6L7k.jpg",
          release_date: "1984-05-23",
          title: "Once Upon a Time in America",
          video: false,
          vote_average: 8.41,
          vote_count: 5636,
        },
        {
          adult: false,
          backdrop_path: "/4Nx40jwpoTHPjCWNGoaZ6kaoGxa.jpg",
          genre_ids: [18],
          id: 255709,
          original_language: "ko",
          original_title: "소원",
          overview:
            "After 8-year-old So-won narrowly survives a brutal sexual assault, her family labors to help her heal while coping with their own rage and grief.",
          popularity: 5.7641,
          poster_path: "/x9yjkm9gIz5qI5fJMUTfBnWiB2o.jpg",
          release_date: "2013-10-02",
          title: "Hope",
          video: false,
          vote_average: 8.397,
          vote_count: 787,
        },
        {
          adult: false,
          backdrop_path: "/5lAMQMWpXMsirvtLLvW7cJgEPkU.jpg",
          genre_ids: [16, 18, 10749],
          id: 378064,
          original_language: "ja",
          original_title: "映画 聲の形",
          overview:
            "Shouya Ishida starts bullying the new girl in class, Shouko Nishimiya, because she is deaf. But as the teasing continues, the rest of the class starts to turn on Shouya for his lack of compassion. When they leave elementary school, Shouko and Shouya do not speak to each other again... until an older, wiser Shouya, tormented by his past behaviour, decides he must see Shouko once more. He wants to atone for his sins, but is it already too late...?",
          popularity: 9.9964,
          poster_path: "/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg",
          release_date: "2016-09-17",
          title: "A Silent Voice: The Movie",
          video: false,
          vote_average: 8.4,
          vote_count: 4147,
        },
        {
          adult: false,
          backdrop_path: "/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg",
          genre_ids: [10749, 18],
          id: 724089,
          original_language: "en",
          original_title: "Gabriel's Inferno: Part II",
          overview:
            "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
          popularity: 1.2077,
          poster_path: "/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg",
          release_date: "2020-07-31",
          title: "Gabriel's Inferno: Part II",
          video: false,
          vote_average: 8.381,
          vote_count: 1524,
        },
        {
          adult: false,
          backdrop_path: "/1XqIhsqnAozznGhxlGdI0GPcCro.jpg",
          genre_ids: [18, 10752],
          id: 423,
          original_language: "en",
          original_title: "The Pianist",
          overview:
            "The true story of pianist Władysław Szpilman's experiences in Warsaw during the Nazi occupation. When the Jews of the city find themselves forced into a ghetto, Szpilman finds work playing in a café; and when his family is deported in 1942, he stays behind, works for a while as a laborer, and eventually goes into hiding in the ruins of the war-torn city.",
          popularity: 10.0173,
          poster_path: "/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
          release_date: "2002-09-17",
          title: "The Pianist",
          video: false,
          vote_average: 8.38,
          vote_count: 9562,
        },
        {
          adult: false,
          backdrop_path: "/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg",
          genre_ids: [18, 10402],
          id: 244786,
          original_language: "en",
          original_title: "Whiplash",
          overview:
            "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
          popularity: 18.9158,
          poster_path: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
          release_date: "2014-10-10",
          title: "Whiplash",
          video: false,
          vote_average: 8.4,
          vote_count: 15714,
        },
      ],
    },
  },
  {
    genreId: 27,
    genreName: "Horror",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/uif5fUshJrXyyDzfpzp1DLw3N0S.jpg",
          genre_ids: [27, 53, 9648],
          id: 539,
          original_language: "en",
          original_title: "Psycho",
          overview:
            "When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother.",
          popularity: 11.4603,
          poster_path: "/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg",
          release_date: "1960-06-22",
          title: "Psycho",
          video: false,
          vote_average: 8.4,
          vote_count: 10400,
        },
      ],
    },
  },

  {
    genreId: 28,
    genreName: "Action",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/enNubozHn9pXi0ycTVYUWfpHZm.jpg",
          genre_ids: [18, 28, 80, 53],
          id: 155,
          original_language: "en",
          original_title: "The Dark Knight",
          overview:
            "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
          popularity: 20.3922,
          poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
          release_date: "2008-07-16",
          title: "The Dark Knight",
          video: false,
          vote_average: 8.52,
          vote_count: 33960,
        },
        {
          adult: false,
          backdrop_path: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
          genre_ids: [12, 14, 28],
          id: 122,
          original_language: "en",
          original_title: "The Lord of the Rings: The Return of the King",
          overview:
            "As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.​",
          popularity: 18.4545,
          poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
          release_date: "2003-12-17",
          title: "The Lord of the Rings: The Return of the King",
          video: false,
          vote_average: 8.486,
          vote_count: 25151,
        },
        {
          adult: false,
          backdrop_path: "/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg",
          genre_ids: [28, 18],
          id: 346,
          original_language: "ja",
          original_title: "七人の侍",
          overview:
            "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
          popularity: 8.0693,
          poster_path: "/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg",
          release_date: "1954-04-26",
          title: "Seven Samurai",
          video: false,
          vote_average: 8.456,
          vote_count: 3910,
        },
        {
          adult: false,
          backdrop_path: "/nC3IjYhUgZWgfKfFX0ygMigFwgc.jpg",
          genre_ids: [28, 18, 36],
          id: 14537,
          original_language: "ja",
          original_title: "切腹",
          overview:
            "Down-on-his-luck veteran Tsugumo Hanshirō enters the courtyard of the prosperous House of Iyi. Unemployed, and with no family, he hopes to find a place to commit seppuku—and a worthy second to deliver the coup de grâce in his suicide ritual. The senior counselor for the Iyi clan questions the ronin’s resolve and integrity, suspecting Hanshirō of seeking charity rather than an honorable end. What follows is a pair of interlocking stories which lay bare the difference between honor and respect, and promises to examine the legendary foundations of the Samurai code.",
          popularity: 4.7752,
          poster_path: "/5konZnIbcAxZjP616Cz5o9bKEfW.jpg",
          release_date: "1962-09-15",
          title: "Harakiri",
          video: false,
          vote_average: 8.423,
          vote_count: 1088,
        },
        {
          adult: false,
          backdrop_path: "/x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg",
          genre_ids: [12, 14, 28],
          id: 120,
          original_language: "en",
          original_title: "The Lord of the Rings: The Fellowship of the Ring",
          overview:
            "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.",
          popularity: 25.2971,
          poster_path: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
          release_date: "2001-12-18",
          title: "The Lord of the Rings: The Fellowship of the Ring",
          video: false,
          vote_average: 8.423,
          vote_count: 26065,
        },
        {
          adult: false,
          backdrop_path: "/jfEOzpsjc6JDlKhUHb4toWQPt.jpg",
          genre_ids: [12, 14, 28],
          id: 121,
          original_language: "en",
          original_title: "The Lord of the Rings: The Two Towers",
          overview:
            "Frodo Baggins and the other members of the Fellowship continue on their sacred quest to destroy the One Ring--but on separate paths. Their destinies lie at two towers--Orthanc Tower in Isengard, where the corrupt wizard Saruman awaits, and Sauron's fortress at Barad-dur, deep within the dark lands of Mordor. Frodo and Sam are trekking to Mordor to destroy the One Ring of Power while Gimli, Legolas and Aragorn search for the orc-captured Merry and Pippin. All along, nefarious wizard Saruman awaits the Fellowship members at the Orthanc Tower in Isengard.",
          popularity: 15.902,
          poster_path: "/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
          release_date: "2002-12-18",
          title: "The Lord of the Rings: The Two Towers",
          video: false,
          vote_average: 8.407,
          vote_count: 22661,
        },
        {
          adult: false,
          backdrop_path: "/8mnXR9rey5uQ08rZAvzojKWbDQS.jpg",
          genre_ids: [16, 28, 12, 878],
          id: 324857,
          original_language: "en",
          original_title: "Spider-Man: Into the Spider-Verse",
          overview:
            'Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson "Kingpin" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension.',
          popularity: 18.0963,
          poster_path: "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
          release_date: "2018-12-06",
          title: "Spider-Man: Into the Spider-Verse",
          video: false,
          vote_average: 8.399,
          vote_count: 16210,
        },
        {
          adult: false,
          backdrop_path: "/kgjvZgs6cV2v5bigzzzWqJ9EMGs.jpg",
          genre_ids: [12, 28, 878],
          id: 1891,
          original_language: "en",
          original_title: "The Empire Strikes Back",
          overview:
            "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.",
          popularity: 8.9603,
          poster_path: "/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
          release_date: "1980-05-20",
          title: "The Empire Strikes Back",
          video: false,
          vote_average: 8.396,
          vote_count: 17478,
        },
      ],
    },
  },
  {
    genreId: 35,
    genreName: "Comedy",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
          genre_ids: [35, 18, 10749],
          id: 19404,
          original_language: "hi",
          original_title: "दिलवाले दुल्हनिया ले जायेंगे",
          overview:
            "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
          popularity: 8.0918,
          poster_path: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
          release_date: "1995-10-20",
          title: "Dilwale Dulhania Le Jayenge",
          video: false,
          vote_average: 8.517,
          vote_count: 4490,
        },
        {
          adult: false,
          backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
          genre_ids: [35, 53, 18],
          id: 496243,
          original_language: "ko",
          original_title: "기생충",
          overview:
            "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
          popularity: 22.8694,
          poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
          release_date: "2019-05-30",
          title: "Parasite",
          video: false,
          vote_average: 8.499,
          vote_count: 19135,
        },
        {
          adult: false,
          backdrop_path: "/tlEFuIlaxRPXIYVHXbOSAMCfWqk.jpg",
          genre_ids: [35, 18, 10749],
          id: 13,
          original_language: "en",
          original_title: "Forrest Gump",
          overview:
            "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
          popularity: 17.8749,
          poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
          release_date: "1994-06-23",
          title: "Forrest Gump",
          video: false,
          vote_average: 8.468,
          vote_count: 28295,
        },
        {
          adult: false,
          backdrop_path: "/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg",
          genre_ids: [35, 18],
          id: 637,
          original_language: "it",
          original_title: "La vita è bella",
          overview:
            "A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.",
          popularity: 10.5656,
          poster_path: "/74hLDKjD5aGYOotO6esUVaeISa2.jpg",
          release_date: "1997-12-20",
          title: "Life Is Beautiful",
          video: false,
          vote_average: 8.447,
          vote_count: 13400,
        },
        {
          adult: false,
          backdrop_path: "/alQqTpmEkxSLgajfEYTsTH6nAKB.jpg",
          genre_ids: [35, 18, 14],
          id: 40096,
          original_language: "pt",
          original_title: "O Auto da Compadecida",
          overview:
            "The lively João Grilo and the sly Chicó are poor guys living in the hinterland who cheat a bunch of people in a small town in Northeastern Brazil. When they die, they have to be judged by Christ, the Devil and the Virgin Mary before they are admitted to paradise.",
          popularity: 2.0711,
          poster_path: "/aovknfdLnFp1IiWi3yvTAg8Gm5k.jpg",
          release_date: "2000-09-15",
          title: "A Dog's Will",
          video: false,
          vote_average: 8.4,
          vote_count: 1165,
        },
      ],
    },
  },

  {
    genreId: 36,
    genreName: "History",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
          genre_ids: [18, 36, 10752],
          id: 424,
          original_language: "en",
          original_title: "Schindler's List",
          overview:
            "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
          popularity: 12.5664,
          poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
          release_date: "1993-12-15",
          title: "Schindler's List",
          video: false,
          vote_average: 8.564,
          vote_count: 16479,
        },
        {
          adult: false,
          backdrop_path: "/nC3IjYhUgZWgfKfFX0ygMigFwgc.jpg",
          genre_ids: [28, 18, 36],
          id: 14537,
          original_language: "ja",
          original_title: "切腹",
          overview:
            "Down-on-his-luck veteran Tsugumo Hanshirō enters the courtyard of the prosperous House of Iyi. Unemployed, and with no family, he hopes to find a place to commit seppuku—and a worthy second to deliver the coup de grâce in his suicide ritual. The senior counselor for the Iyi clan questions the ronin’s resolve and integrity, suspecting Hanshirō of seeking charity rather than an honorable end. What follows is a pair of interlocking stories which lay bare the difference between honor and respect, and promises to examine the legendary foundations of the Samurai code.",
          popularity: 4.7752,
          poster_path: "/5konZnIbcAxZjP616Cz5o9bKEfW.jpg",
          release_date: "1962-09-15",
          title: "Harakiri",
          video: false,
          vote_average: 8.423,
          vote_count: 1088,
        },
      ],
    },
  },
  {
    genreId: 37,
    genreName: "Western",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/x4biAVdPVCghBlsVIzB6NmbghIz.jpg",
          genre_ids: [37],
          id: 429,
          original_language: "it",
          original_title: "Il buono, il brutto, il cattivo",
          overview:
            "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
          popularity: 21.2469,
          poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
          release_date: "1966-12-22",
          title: "The Good, the Bad and the Ugly",
          video: false,
          vote_average: 8.462,
          vote_count: 9029,
        },
      ],
    },
  },

  {
    genreId: 53,
    genreName: "Thriller",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/enNubozHn9pXi0ycTVYUWfpHZm.jpg",
          genre_ids: [18, 28, 80, 53],
          id: 155,
          original_language: "en",
          original_title: "The Dark Knight",
          overview:
            "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
          popularity: 20.3922,
          poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
          release_date: "2008-07-16",
          title: "The Dark Knight",
          video: false,
          vote_average: 8.52,
          vote_count: 33960,
        },
        {
          adult: false,
          backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
          genre_ids: [35, 53, 18],
          id: 496243,
          original_language: "ko",
          original_title: "기생충",
          overview:
            "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
          popularity: 22.8694,
          poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
          release_date: "2019-05-30",
          title: "Parasite",
          video: false,
          vote_average: 8.499,
          vote_count: 19135,
        },
        {
          adult: false,
          backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
          genre_ids: [53, 80],
          id: 680,
          original_language: "en",
          original_title: "Pulp Fiction",
          overview:
            "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
          popularity: 18.2615,
          poster_path: "/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
          release_date: "1994-09-10",
          title: "Pulp Fiction",
          video: false,
          vote_average: 8.5,
          vote_count: 28763,
        },
        {
          adult: false,
          backdrop_path: "/uif5fUshJrXyyDzfpzp1DLw3N0S.jpg",
          genre_ids: [27, 53, 9648],
          id: 539,
          original_language: "en",
          original_title: "Psycho",
          overview:
            "When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother.",
          popularity: 11.4603,
          poster_path: "/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg",
          release_date: "1960-06-22",
          title: "Psycho",
          video: false,
          vote_average: 8.4,
          vote_count: 10400,
        },
      ],
    },
  },

  {
    genreId: 80,
    genreName: "Crime",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
          genre_ids: [18, 80],
          id: 278,
          original_language: "en",
          original_title: "The Shawshank Redemption",
          overview:
            "Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
          popularity: 32.9479,
          poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
          release_date: "1994-09-23",
          title: "The Shawshank Redemption",
          video: false,
          vote_average: 8.711,
          vote_count: 28443,
        },
        {
          adult: false,
          backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
          genre_ids: [18, 80],
          id: 238,
          original_language: "en",
          original_title: "The Godfather",
          overview:
            "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
          popularity: 36.0976,
          poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
          release_date: "1972-03-14",
          title: "The Godfather",
          video: false,
          vote_average: 8.686,
          vote_count: 21540,
        },
        {
          adult: false,
          backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
          genre_ids: [18, 80],
          id: 240,
          original_language: "en",
          original_title: "The Godfather Part II",
          overview:
            "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
          popularity: 16.1032,
          poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
          release_date: "1974-12-20",
          title: "The Godfather Part II",
          video: false,
          vote_average: 8.571,
          vote_count: 13007,
        },
        {
          adult: false,
          backdrop_path: "/enNubozHn9pXi0ycTVYUWfpHZm.jpg",
          genre_ids: [18, 28, 80, 53],
          id: 155,
          original_language: "en",
          original_title: "The Dark Knight",
          overview:
            "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
          popularity: 20.3922,
          poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
          release_date: "2008-07-16",
          title: "The Dark Knight",
          video: false,
          vote_average: 8.52,
          vote_count: 33960,
        },
        {
          adult: false,
          backdrop_path: "/amZavErrjrdgDwhsIdpWxHNenIx.jpg",
          genre_ids: [14, 18, 80],
          id: 497,
          original_language: "en",
          original_title: "The Green Mile",
          overview:
            "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
          popularity: 16.8896,
          poster_path: "/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg",
          release_date: "1999-12-10",
          title: "The Green Mile",
          video: false,
          vote_average: 8.505,
          vote_count: 18143,
        },
        {
          adult: false,
          backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
          genre_ids: [53, 80],
          id: 680,
          original_language: "en",
          original_title: "Pulp Fiction",
          overview:
            "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
          popularity: 18.2615,
          poster_path: "/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg",
          release_date: "1994-09-10",
          title: "Pulp Fiction",
          video: false,
          vote_average: 8.5,
          vote_count: 28763,
        },
        {
          adult: false,
          backdrop_path: "/7TF4p86ZafnxFuNqWdhpHXFO244.jpg",
          genre_ids: [18, 80],
          id: 769,
          original_language: "en",
          original_title: "GoodFellas",
          overview:
            "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
          popularity: 13.653,
          poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
          release_date: "1990-09-12",
          title: "GoodFellas",
          video: false,
          vote_average: 8.454,
          vote_count: 13427,
        },
        {
          adult: false,
          backdrop_path: "/uvitbjFU4JqvMwIkMWHp69bmUzG.jpg",
          genre_ids: [18, 80],
          id: 598,
          original_language: "pt",
          original_title: "Cidade de Deus",
          overview:
            "In the poverty-stricken favelas of Rio de Janeiro in the 1970s, two young men choose different paths. Rocket is a budding photographer who documents the increasing drug-related violence of his neighborhood, while José “Zé” Pequeno is an ambitious drug dealer diving into a dangerous life of crime.",
          popularity: 7.6888,
          poster_path: "/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg",
          release_date: "2002-08-30",
          title: "City of God",
          video: false,
          vote_average: 8.43,
          vote_count: 7684,
        },
        {
          adult: false,
          backdrop_path: "/uPYa165sraN2c8gZBM9C47g3JoU.jpg",
          genre_ids: [18, 80],
          id: 311,
          original_language: "en",
          original_title: "Once Upon a Time in America",
          overview:
            "A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan over thirty years later, where he once again must confront the ghosts and regrets of his old life.",
          popularity: 8.8344,
          poster_path: "/i0enkzsL5dPeneWnjl1fCWm6L7k.jpg",
          release_date: "1984-05-23",
          title: "Once Upon a Time in America",
          video: false,
          vote_average: 8.41,
          vote_count: 5636,
        },
      ],
    },
  },
  {
    genreId: 878,
    genreName: "Science Fiction",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/l33oR0mnvf20avWyIMxW02EtQxn.jpg",
          genre_ids: [12, 18, 878],
          id: 157336,
          original_language: "en",
          original_title: "Interstellar",
          overview:
            "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
          popularity: 35.8128,
          poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
          release_date: "2014-11-05",
          title: "Interstellar",
          video: false,
          vote_average: 8.455,
          vote_count: 37289,
        },
        {
          adult: false,
          backdrop_path: "/8mnXR9rey5uQ08rZAvzojKWbDQS.jpg",
          genre_ids: [16, 28, 12, 878],
          id: 324857,
          original_language: "en",
          original_title: "Spider-Man: Into the Spider-Verse",
          overview:
            'Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson "Kingpin" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension.',
          popularity: 18.0963,
          poster_path: "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
          release_date: "2018-12-06",
          title: "Spider-Man: Into the Spider-Verse",
          video: false,
          vote_average: 8.399,
          vote_count: 16210,
        },
        {
          adult: false,
          backdrop_path: "/kgjvZgs6cV2v5bigzzzWqJ9EMGs.jpg",
          genre_ids: [12, 28, 878],
          id: 1891,
          original_language: "en",
          original_title: "The Empire Strikes Back",
          overview:
            "The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.",
          popularity: 8.9603,
          poster_path: "/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
          release_date: "1980-05-20",
          title: "The Empire Strikes Back",
          video: false,
          vote_average: 8.396,
          vote_count: 17478,
        },
      ],
    },
  },

  {
    genreId: 9648,
    genreName: "Mystery",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/uif5fUshJrXyyDzfpzp1DLw3N0S.jpg",
          genre_ids: [27, 53, 9648],
          id: 539,
          original_language: "en",
          original_title: "Psycho",
          overview:
            "When larcenous real estate clerk Marion Crane goes on the lam with a wad of cash and hopes of starting a new life, she ends up at the notorious Bates Motel, where manager Norman Bates cares for his housebound mother.",
          popularity: 11.4603,
          poster_path: "/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg",
          release_date: "1960-06-22",
          title: "Psycho",
          video: false,
          vote_average: 8.4,
          vote_count: 10400,
        },
      ],
    },
  },

  {
    genreId: 10402,
    genreName: "Music",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/fRGxZuo7jJUWQsVg9PREb98Aclp.jpg",
          genre_ids: [18, 10402],
          id: 244786,
          original_language: "en",
          original_title: "Whiplash",
          overview:
            "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
          popularity: 18.9158,
          poster_path: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
          release_date: "2014-10-10",
          title: "Whiplash",
          video: false,
          vote_average: 8.4,
          vote_count: 15714,
        },
      ],
    },
  },

  {
    genreId: 10749,
    genreName: "Romance",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
          genre_ids: [35, 18, 10749],
          id: 19404,
          original_language: "hi",
          original_title: "दिलवाले दुल्हनिया ले जायेंगे",
          overview:
            "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
          popularity: 8.0918,
          poster_path: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
          release_date: "1995-10-20",
          title: "Dilwale Dulhania Le Jayenge",
          video: false,
          vote_average: 8.517,
          vote_count: 4490,
        },
        {
          adult: false,
          backdrop_path: "/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg",
          genre_ids: [16, 10749, 18],
          id: 372058,
          original_language: "ja",
          original_title: "君の名は。",
          overview:
            "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
          popularity: 20.7912,
          poster_path: "/8GJsy7w7frGquw1cy9jasOGNNI1.jpg",
          release_date: "2016-08-26",
          title: "Your Name.",
          video: false,
          vote_average: 8.482,
          vote_count: 11812,
        },
        {
          adult: false,
          backdrop_path: "/tlEFuIlaxRPXIYVHXbOSAMCfWqk.jpg",
          genre_ids: [35, 18, 10749],
          id: 13,
          original_language: "en",
          original_title: "Forrest Gump",
          overview:
            "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
          popularity: 17.8749,
          poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
          release_date: "1994-06-23",
          title: "Forrest Gump",
          video: false,
          vote_average: 8.468,
          vote_count: 28295,
        },
        {
          adult: false,
          backdrop_path: "/k3SBILYxHRgjORb5tbvA5dm2N4h.jpg",
          genre_ids: [18, 10749],
          id: 11216,
          original_language: "it",
          original_title: "Nuovo Cinema Paradiso",
          overview:
            "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
          popularity: 5.3075,
          poster_path: "/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg",
          release_date: "1988-11-17",
          title: "Cinema Paradiso",
          video: false,
          vote_average: 8.4,
          vote_count: 4544,
        },
        {
          adult: false,
          backdrop_path: "/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg",
          genre_ids: [10749, 18],
          id: 696374,
          original_language: "en",
          original_title: "Gabriel's Inferno",
          overview:
            "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
          popularity: 2.3924,
          poster_path: "/yXRoyYzIo17HfANn07oXYdyBy4h.jpg",
          release_date: "2020-05-29",
          title: "Gabriel's Inferno",
          video: false,
          vote_average: 8.411,
          vote_count: 2424,
        },
        {
          adult: false,
          backdrop_path: "/5lAMQMWpXMsirvtLLvW7cJgEPkU.jpg",
          genre_ids: [16, 18, 10749],
          id: 378064,
          original_language: "ja",
          original_title: "映画 聲の形",
          overview:
            "Shouya Ishida starts bullying the new girl in class, Shouko Nishimiya, because she is deaf. But as the teasing continues, the rest of the class starts to turn on Shouya for his lack of compassion. When they leave elementary school, Shouko and Shouya do not speak to each other again... until an older, wiser Shouya, tormented by his past behaviour, decides he must see Shouko once more. He wants to atone for his sins, but is it already too late...?",
          popularity: 9.9964,
          poster_path: "/tuFaWiqX0TXoWu7DGNcmX3UW7sT.jpg",
          release_date: "2016-09-17",
          title: "A Silent Voice: The Movie",
          video: false,
          vote_average: 8.4,
          vote_count: 4147,
        },
        {
          adult: false,
          backdrop_path: "/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg",
          genre_ids: [10749, 18],
          id: 724089,
          original_language: "en",
          original_title: "Gabriel's Inferno: Part II",
          overview:
            "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
          popularity: 1.2077,
          poster_path: "/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg",
          release_date: "2020-07-31",
          title: "Gabriel's Inferno: Part II",
          video: false,
          vote_average: 8.381,
          vote_count: 1524,
        },
      ],
    },
  },

  {
    genreId: 10751,
    genreName: "Family",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg",
          genre_ids: [16, 10751, 14],
          id: 129,
          original_language: "ja",
          original_title: "千と千尋の神隠し",
          overview:
            "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
          popularity: 18.5441,
          poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
          release_date: "2001-07-20",
          title: "Spirited Away",
          video: false,
          vote_average: 8.536,
          vote_count: 17212,
        },
        {
          adult: false,
          backdrop_path: "/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg",
          genre_ids: [10751, 18],
          id: 667257,
          original_language: "es",
          original_title: "Cosas imposibles",
          overview:
            "After the death of her abusive husband, Matilde finds her new best friend in Miguel, her young, insecure, and disoriented neighbor.",
          popularity: 0.9881,
          poster_path: "/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg",
          release_date: "2021-06-17",
          title: "Impossible Things",
          video: false,
          vote_average: 8.43,
          vote_count: 410,
        },
      ],
    },
  },

  {
    genreId: 10752,
    genreName: "War",
    allPagesMovies: {
      results: [
        {
          adult: false,
          backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
          genre_ids: [18, 36, 10752],
          id: 424,
          original_language: "en",
          original_title: "Schindler's List",
          overview:
            "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
          popularity: 12.5664,
          poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
          release_date: "1993-12-15",
          title: "Schindler's List",
          video: false,
          vote_average: 8.564,
          vote_count: 16479,
        },
        {
          adult: false,
          backdrop_path: "/tDFvXn4tane9lUvFAFAUkMylwSr.jpg",
          genre_ids: [16, 18, 10752],
          id: 12477,
          original_language: "ja",
          original_title: "火垂るの墓",
          overview:
            "In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.",
          popularity: 0.0094,
          poster_path: "/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg",
          release_date: "1988-04-16",
          title: "Grave of the Fireflies",
          video: false,
          vote_average: 8.448,
          vote_count: 5924,
        },
        {
          adult: false,
          backdrop_path: "/1XqIhsqnAozznGhxlGdI0GPcCro.jpg",
          genre_ids: [18, 10752],
          id: 423,
          original_language: "en",
          original_title: "The Pianist",
          overview:
            "The true story of pianist Władysław Szpilman's experiences in Warsaw during the Nazi occupation. When the Jews of the city find themselves forced into a ghetto, Szpilman finds work playing in a café; and when his family is deported in 1942, he stays behind, works for a while as a laborer, and eventually goes into hiding in the ruins of the war-torn city.",
          popularity: 10.0173,
          poster_path: "/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg",
          release_date: "2002-09-17",
          title: "The Pianist",
          video: false,
          vote_average: 8.38,
          vote_count: 9562,
        },
      ],
    },
  },
];
